/*
 * UPF Event Exposure Service
 *
 * UPF Event Exposure Service.   © 2024, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved.
 *
 * API version: 1.1.0-alpha.5
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package nupf

import (
	"net"
	"time"
)

// represents a report on one subscribed event
type NotificationItem struct {
	EventType string `json:"eventType"`

	UeIpv4Addr net.IP `json:"ueIpv4Addr,omitempty"`

	UeIpv6Prefix net.IP `json:"ueIpv6Prefix,omitempty"`

	UeMacAddr string `json:"ueMacAddr,omitempty"`

	Dnn string `json:"dnn,omitempty"`

	Snssai *Snssai `json:"snssai,omitempty"`

	Gpsi string `json:"gpsi,omitempty"`

	Supi string `json:"supi,omitempty"`

	TimeStamp *time.Time `json:"timeStamp"`

	StartTime *time.Time `json:"startTime,omitempty"`

	QosMonitoringMeasurement *QosMonitoringMeasurement `json:"qosMonitoringMeasurement,omitempty"`

	TscMngtInfo *TscManagementInfo `json:"tscMngtInfo,omitempty"`

	UserDataUsageMeasurements []UserDataUsageMeasurements `json:"userDataUsageMeasurements,omitempty"`
}
