/*
 * UPF Event Exposure Service
 *
 * UPF Event Exposure Service.   © 2024, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved.
 *
 * API version: 1.1.0-alpha.5
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package nupf

// Indicates the Event producer NF settings to the Event consumer NF
type MutingNotificationsSettings struct {
	MaxNoOfNotif int32 `json:"maxNoOfNotif,omitempty"`

	DurationBufferedNotif int32 `json:"durationBufferedNotif,omitempty"`
}
