/*
 * UPF Event Exposure Service
 *
 * UPF Event Exposure Service.   © 2024, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved.
 *
 * API version: 1.1.0-alpha.5
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package nupf

// UPF Event
type UpfEvent struct {
	Type_ string `json:"type"` // QOS_MONITORING USER_DATA_USAGE_MEASURES USER_DATA_USAGE_TRENDS TSC_MNGT_INFO PER_FLOW_USAGE_MEASURES

	ImmediateFlag bool `json:"immediateFlag,omitempty"`

	MeasurementTypes []string `json:"measurementTypes,omitempty"` // VOLUME_MEASUREMENT THROUGHPUT_MEASUREMENT APPLICATION_RELATED_INFO

	AppIds []string `json:"appIds,omitempty"`

	TrafficFilters []FlowInformation `json:"trafficFilters,omitempty"`

	GranularityOfMeasurement string `json:"granularityOfMeasurement,omitempty"` // PER_APPLICATION PER_SESSION PER_FLOW

	ReportingSuggestionInfo *ReportingSuggestionInformation `json:"reportingSuggestionInfo,omitempty"`
}
