/*
 * UPF Event Exposure Service
 *
 * UPF Event Exposure Service.   © 2024, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved.
 *
 * API version: 1.1.0-alpha.5
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package nupf

// QoS Monitoring Measurement information
type QosMonitoringMeasurement struct {
	DlPacketDelay int32 `json:"dlPacketDelay,omitempty"`

	UlPacketDelay int32 `json:"ulPacketDelay,omitempty"`

	RtrPacketDelay int32 `json:"rtrPacketDelay,omitempty"`

	MeasureFailure bool `json:"measureFailure,omitempty"`

	DlAveThroughput string `json:"dlAveThroughput,omitempty"`

	UlAveThroughput string `json:"ulAveThroughput,omitempty"`

	DlCongestion int32 `json:"dlCongestion,omitempty"`

	UlCongestion int32 `json:"ulCongestion,omitempty"`

	DefaultQosFlowInd bool `json:"defaultQosFlowInd,omitempty"`
}
