/*
 * UPF Event Exposure Service
 *
 * UPF Event Exposure Service.   © 2024, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved.
 *
 * API version: 1.1.0-alpha.5
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package nupf

// Throughput Statistics Measurement
type ThroughputStatisticsMeasurement struct {
	UlAverageThroughput string `json:"ulAverageThroughput,omitempty"`

	DlAverageThroughput string `json:"dlAverageThroughput,omitempty"`

	UlPeakThroughput string `json:"ulPeakThroughput,omitempty"`

	DlPeakThroughPut string `json:"dlPeakThroughPut,omitempty"`

	UlAveragePacketThroughput string `json:"ulAveragePacketThroughput,omitempty"`

	DlAveragePacketThroughput string `json:"dlAveragePacketThroughput,omitempty"`

	UlPeakPacketThroughput string `json:"ulPeakPacketThroughput,omitempty"`

	DlPeakPacketThroughput string `json:"dlPeakPacketThroughput,omitempty"`
}
