/*
 * UPF Event Exposure Service
 *
 * UPF Event Exposure Service.   © 2024, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved.
 *
 * API version: 1.1.0-alpha.5
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package nupf

// Contains the flow information.
type FlowInformation struct {
	FlowDescription string `json:"flowDescription,omitempty"`

	EthFlowDescription *EthFlowDescription `json:"ethFlowDescription,omitempty"`
	// An identifier of packet filter.
	PackFiltId string `json:"packFiltId,omitempty"`
	// The packet shall be sent to the UE.
	PacketFilterUsage bool `json:"packetFilterUsage,omitempty"`
	// Contains the Ipv4 Type-of-Service and mask field or the Ipv6 Traffic-Class field and  mask field.
	TosTrafficClass string `json:"tosTrafficClass,omitempty"`
	// the security parameter index of the IPSec packet.
	Spi string `json:"spi,omitempty"`
	// the Ipv6 flow label header field.
	FlowLabel string `json:"flowLabel,omitempty"`

	FlowDirection string `json:"flowDirection,omitempty"` // DOWNLINK UPLINK BIDIRECTIONAL UNSPECIFIED
}
