/*
 * UPF Event Exposure Service
 *
 * UPF Event Exposure Service.   © 2024, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved.
 *
 * API version: 1.1.0-alpha.5
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package nupf

import "net"

// Contains an IP adresse.
type IpAddr struct {
	Ipv4Addr net.IP `json:"ipv4Addr,omitempty"`

	Ipv6Addr string `json:"ipv6Addr,omitempty"`

	Ipv6Prefix string `json:"ipv6Prefix,omitempty"`
}
