/*
 * UPF Event Exposure Service
 *
 * UPF Event Exposure Service.   © 2024, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved.
 *
 * API version: 1.1.0-alpha.5
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package nupf

// Indicates to an Event producer NF instructions for the subscription and stored events when an exception (e.g. full buffer) occurs at the Event producer NF while the event is muted.
type MutingExceptionInstructions struct {
	BufferedNotifs string `json:"bufferedNotifs,omitempty"` // SEND_ALL DISCARD_ALL DROP_OLD

	Subscription string `json:"subscription,omitempty"` // CLOSE CONTINUE_WITH_MUTING CONTINUE_WITHOUT_MUTING
}
