/*
 * UPF Event Exposure Service
 *
 * UPF Event Exposure Service.   © 2024, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved.
 *
 * API version: 1.1.0-alpha.5
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package nupf

// User Data Usage Measurements either for the PDU session, or the app-id, or the data flow
type UserDataUsageMeasurements struct {
	AppId string `json:"appId,omitempty"`

	FlowInfo *FlowInformation `json:"flowInfo,omitempty"`

	VolumeMeasurement *VolumeMeasurement `json:"volumeMeasurement,omitempty"`

	ThroughputMeasurement *ThroughputMeasurement `json:"throughputMeasurement,omitempty"`

	ApplicationRelatedInformation *ApplicationRelatedInformation `json:"applicationRelatedInformation,omitempty"`

	ThroughputStatisticsMeasurement *ThroughputStatisticsMeasurement `json:"throughputStatisticsMeasurement,omitempty"`
}
