/*
 * UPF Event Exposure Service
 *
 * UPF Event Exposure Service.   © 2024, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved.
 *
 * API version: 1.1.0-alpha.5
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package nupf

// UPF Event Subscription
type UpfEventSubscription struct {
	EventList []UpfEvent `json:"eventList"`

	EventNotifyUri string `json:"eventNotifyUri"`

	NotifyCorrelationId string `json:"notifyCorrelationId"`

	EventReportingMode *UpfEventMode `json:"eventReportingMode"`

	NfId string `json:"nfId"`

	UeIpAddress *IpAddr `json:"ueIpAddress,omitempty"`

	Supi string `json:"supi,omitempty"`

	Gpsi string `json:"gpsi,omitempty"`

	Pei string `json:"pei,omitempty"`

	AnyUe bool `json:"anyUe,omitempty"`

	Dnn string `json:"dnn,omitempty"`

	Snssai *Snssai `json:"snssai,omitempty"`
}
