/*
 * UPF Event Exposure Service
 *
 * UPF Event Exposure Service.   © 2024, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved.
 *
 * API version: 1.1.0-alpha.5
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package nupf

// Reporting Suggestion Information
type ReportingSuggestionInformation struct {
	ReportingUrgency string `json:"reportingUrgency"` // DELAY_TOLERANT NON_DELAY_TOLERANT

	ReportingTimeInfo int32 `json:"reportingTimeInfo,omitempty"`
}
