/*
 * UPF Event Exposure Service
 *
 * UPF Event Exposure Service.   © 2024, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved.
 *
 * API version: 1.1.0-alpha.5
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package nupf

// Provides the reason for not finding NF matching the search criteria
type NoProfileMatchInfo struct {
	Reason string `json:"reason"` // REQUESTER_PLMN_NOT_ALLOWED TARGET_NF_SUSPENDED TARGET_NF_UNDISCOVERABLE QUERY_PARAMS_COMBINATION_NO_MATCH TARGET_NF_TYPE_NOT_SUPPORTED UNSPECIFIED

	QueryParamCombinationList []QueryParamCombination `json:"queryParamCombinationList,omitempty"`
}
